# Generated by Django 3.2.9 on 2021-12-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
