# Generated by Django 3.2.9 on 2021-12-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ManyToManyField(blank=True, to='boards.Category'),
        ),
    ]
