# Generated by Django 3.2.9 on 2021-12-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_alter_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
