# Generated by Django 3.2.9 on 2021-12-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
