# Generated by Django 3.2.9 on 2021-12-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
